FROM elixir:1.9-alpine

# Create app directory and copy the Elixir projects into it
RUN mkdir /app
COPY . /app
WORKDIR /app

# Install hex package manager
RUN rm -rf deps && rm -rf _build
RUN mix do local.hex --force, local.rebar --force

RUN apk add --update bash openssl postgresql-client

# Compile the project
RUN mix deps.get --only dev
RUN mix deps.compile

RUN mix do compile

RUN chown -R nobody: /app
USER nobody
ENV HOME=/app
#RUN mix do local.hex --force
CMD ["bash", "/app/build_scripts/entrypoint_dev.sh"]
